app:
  users:
#    - igorvood
#    - Jeka1978
#    - lavcraft
#    - xpinjection
    - RSocket
#    - xpinjection
#    - Baeldung
#    - eugenp
#    - yegor256


save:
  folder: D:\temp\github_2022_08_30\