app:
  users:
    - igorvood
    - Jeka1978
    - lavcraft
    - xpinjection
    - RSocket
    - xpinjection
    - Baeldung
    - eugenp
    - yegor256
    - konrad-kaminski


save:
#  folder: D:\temp\github_2022_08_30\
  folder: /home/vood/github/