spring:
  profiles:
    active: login

app:
  users:
    - igorvood
#    - ionspin
    - Jeka1978
    - lavcraft
    - xpinjection
    - RSocket
    - Baeldung
    - eugenp
    - yegor256
    - konrad-kaminski
    - aabarmin
    - spring-framework-guru



save:
#  folder: D:\temp\github_2022_08_30\
  folder: /home/vood/github/