app:
  users:
    - Jeka1978
    - lavcraft
    - igorvood

      #    - xpinjection

      #    - RSocket
#    - xpinjection
#    - Baeldung
#    - eugenp
#    - yegor256


save:
  folder: D:\temp\github_2022_03_17\